package simpleedit;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 * GotoDialog.java
 *
 * @author Eugene Matiyuk (ematiyuk@gmail.com)
 * @year 2012
 */
public class GotoDialog extends javax.swing.JDialog {

    private JTextArea currTextArea;
    private String prgrmName;

    /**
     * Creates new GotoDialog
     *
     * @param parent
     * @param modal
     */
    public GotoDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextLabel = new javax.swing.JLabel();
        jGoToButton = new javax.swing.JButton();
        jInputTextField = new javax.swing.JTextField();
        jCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Переход на строку");
        setIconImage(null);
        setResizable(false);

        jTextLabel.setText("Номер строки:");

        jGoToButton.setText("Переход");
        jGoToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGoToButtonActionPerformed(evt);
            }
        });

        jCancelButton.setText("Отмена");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jGoToButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCancelButton))
                        .addComponent(jInputTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGoToButton)
                    .addComponent(jCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setProgramName(String programName) {
        prgrmName = programName;
    }

    public String getProgramName() {
        return prgrmName;
    }

    public void showDialog() {
        this.setVisible(true);
    }

    public void hideDialog() {
        this.setVisible(false);
    }

    public boolean gotoLine(int lineNumber) {
        if ((lineNumber > 0) && (lineNumber <= Utils.getTextLinesCount(currTextArea.getText()))) {
            int line = 0;
            int firstLineLength = 0;
            int textLength = currTextArea.getText().length();

            for (int i = 0; i < textLength; i++) {
                if (currTextArea.getText().charAt(i) == '\n') {
                    firstLineLength = i;
                    break;
                }
            }

            for (int i = 0; i < textLength; i++) {
                if ((i >= 0) && (i < firstLineLength)) {
                    line = 1;
                } else {
                    if ((currTextArea.getText().charAt(i) == '\n') || (i == (textLength - 1))) {
                        line++;
                    }
                }
                if (line == lineNumber) {
                    if (line == 1) {
                        currTextArea.setCaretPosition(0);
                    } else {
                        currTextArea.setCaretPosition(i + 1);
                    }
                    return true;
                }
            }
            return true;
        } else {
            return false;
        }
    }

    public void setTextArea(JTextArea textarea) {
        currTextArea = textarea;
    }

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.hideDialog();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jGoToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGoToButtonActionPerformed
        if (!jInputTextField.getText().isEmpty()) {
            if (Utils.validateForNumbersOnly(jInputTextField.getText())) {
                int lineNumb = Integer.decode(jInputTextField.getText());
                if (this.gotoLine(lineNumb)) {
                    this.hideDialog();
                } else {
                    String message = "Недопустимый ввод номера строки.";
                    JOptionPane.showMessageDialog(jGoToButton, message, this.getProgramName() + " - Переход на строку", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                String message = "Неверные входные данные.\nДопускаются исключительно цифровые значения.";
                JOptionPane.showMessageDialog(jGoToButton, message, this.getProgramName() + " - Переход на строку", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            String message = "Нет входных данных.\nУкажите, пожалуйста, номер строки.";
            JOptionPane.showMessageDialog(jGoToButton, message, this.getProgramName() + " - Переход на строку", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jGoToButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelButton;
    private javax.swing.JButton jGoToButton;
    private javax.swing.JTextField jInputTextField;
    private javax.swing.JLabel jTextLabel;
    // End of variables declaration//GEN-END:variables
}
